const SUPABASE_URL = "https://cgdyjruyvdekyqsxwdyc.supabase.co";
const SUPABASE_KEY = "sb_publishable__hmbsTSlD7wkcmZdK-LPXg_i-08AJ8_";

const DIVISIONS={"AFC East":["BUF","MIA","NE","NYJ"],"AFC North":["BAL","CIN","CLE","PIT"],"AFC South":["HOU","IND","JAX","TEN"],"AFC West":["DEN","KC","LV","LAC"],"NFC East":["DAL","NYG","PHI","WSH"],"NFC North":["CHI","DET","GB","MIN"],"NFC South":["ATL","CAR","NO","TB"],"NFC West":["ARI","LAR","SF","SEA"]};
const TEAM_NAMES={ARI:"Cardinals",ATL:"Falcons",BAL:"Ravens",BUF:"Bills",CAR:"Panthers",CHI:"Bears",CIN:"Bengals",CLE:"Browns",DAL:"Cowboys",DEN:"Broncos",DET:"Lions",GB:"Packers",HOU:"Texans",IND:"Colts",JAX:"Jaguars",KC:"Chiefs",LV:"Raiders",LAC:"Chargers",LAR:"Rams",MIA:"Dolphins",MIN:"Vikings",NE:"Patriots",NO:"Saints",NYG:"Giants",NYJ:"Jets",PHI:"Eagles",PIT:"Steelers",SF:"49ers",SEA:"Seahawks",TB:"Buccaneers",TEN:"Titans",WSH:"Commanders"};
const CONF={AFC:Object.keys(DIVISIONS).filter(x=>x.startsWith("AFC")).flatMap(x=>DIVISIONS[x]),NFC:Object.keys(DIVISIONS).filter(x=>x.startsWith("NFC")).flatMap(x=>DIVISIONS[x])};
let state={participants:[],picks:[],snapshot:null,conference:"AFC"};

async function api(path,options={}){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});if(!res.ok)throw new Error((await res.text())||`Request failed (${res.status})`);return res.status===204?null:res.json()}
async function load(){try{const [participants,picks,snapshots]=await Promise.all([api("participants?select=*&order=slot"),api("picks?select=*"),api("nfl_snapshot?select=*&id=eq.1")]);state.participants=participants;state.picks=picks;state.snapshot=snapshots[0]||null;render()}catch(e){toast("Could not load the live app. Try again.");console.error(e)}}

function projectedField(){const teams=state.snapshot?.standings?.teams||[];if(!teams.length)return{divisionWinners:{},wildCards:{AFC:[],NFC:[]}};const divisionWinners={};for(const div of Object.keys(DIVISIONS)){const group=teams.filter(t=>t.division===div).sort(sortTeams);if(group[0])divisionWinners[div]=group[0].abbr}const wildCards={AFC:[],NFC:[]};for(const conf of ["AFC","NFC"]){const champs=new Set(Object.entries(divisionWinners).filter(([d])=>d.startsWith(conf)).map(([,t])=>t));wildCards[conf]=teams.filter(t=>t.conference===conf&&!champs.has(t.abbr)).sort(sortTeams).slice(0,3).map(t=>t.abbr)}return{divisionWinners,wildCards}}
function sortTeams(a,b){const seedA=Number(a.playoffSeed)||99,seedB=Number(b.playoffSeed)||99;if(seedA!==seedB)return seedA-seedB;return (b.pct||0)-(a.pct||0)||(b.wins||0)-(a.wins||0)}
function scorePick(pick){const field=projectedField();let projected=0,exact=0,wrong=0;for(const [div,team] of Object.entries(pick?.division_winners||{})){if(field.divisionWinners[div]===team){projected+=3;exact++}else if(field.wildCards[div.slice(0,3)]?.includes(team)){projected+=1;wrong++}}for(const conf of ["AFC","NFC"]){for(const team of pick?.[`${conf.toLowerCase()}_wild_cards`]||[]){if(field.wildCards[conf].includes(team)){projected+=3;exact++}else if(Object.entries(field.divisionWinners).some(([d,t])=>d.startsWith(conf)&&t===team)){projected+=1;wrong++}}}const actual=scorePostseason(pick,state.snapshot?.games||[]);return{projected:projected+actual,regular:projected,postseason:actual,exact,wrong,max:69}}
function scorePostseason(pick,games){let pts=0;const completed=games.filter(g=>g.completed&&g.seasonType===3);const confFinalTeams=new Set(completed.filter(g=>g.week===3).flatMap(g=>g.teams||[]));const sb=completed.find(g=>g.week===5);for(const t of [...(pick?.afc_championship||[]),...(pick?.nfc_championship||[])])if(confFinalTeams.has(t))pts+=3;if(sb){for(const t of pick?.super_bowl||[])if(sb.teams.includes(t))pts+=5;if(pick?.champion===sb.winner)pts+=5}return pts}
function pickFor(id){return state.picks.find(p=>p.participant_id===id)||{participant_id:id,division_winners:{},afc_wild_cards:[],nfc_wild_cards:[],afc_championship:[],nfc_championship:[],super_bowl:[],champion:null}}
function pickCount(p){return Object.keys(p.division_winners||{}).length+(p.afc_wild_cards?.length||0)+(p.nfc_wild_cards?.length||0)+(p.afc_championship?.length||0)+(p.nfc_championship?.length||0)+(p.super_bowl?.length||0)+(p.champion?1:0)}
function esc(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function fmtTime(v){if(!v)return"Waiting for data";return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))}

function render(){renderMeta();renderLeaderboard();renderPickBreakdowns();renderPlayoff();renderBubbleWatch();renderPlayers();renderStandings();renderDashboardStandings()}
function playoffTeamSet(field){return new Set([...Object.values(field.divisionWinners),...(field.wildCards.AFC||[]),...(field.wildCards.NFC||[])])}
function postseasonResults(games=[]){const completed=games.filter(game=>game.completed&&game.seasonType===3),conferenceFinalTeams=new Set(completed.filter(game=>game.week===3).flatMap(game=>game.teams||[])),superBowl=completed.find(game=>game.week===5)||null;return{conferenceFinalTeams,superBowl}}
function teamSnapshot(code){return(state.snapshot?.standings?.teams||[]).find(team=>team.abbr===code)||null}
function recordText(team){if(!team)return"—";return`${team.wins||0}–${team.losses||0}${team.ties?`–${team.ties}`:""}`}
function teamLabel(team){return team?`${esc(team)} · ${esc(TEAM_NAMES[team]||team)}`:"No selection"}
function divisionResult(team,division,field){if(!team||!teamSnapshot(team))return{tone:"neutral",points:0};if(field.divisionWinners[division]===team)return{tone:"good",points:3};if(field.wildCards[division.slice(0,3)]?.includes(team))return{tone:"warning",points:1};return{tone:"bad",points:0}}
function wildCardResult(team,conf,field){if(!team||!teamSnapshot(team))return{tone:"neutral",points:0};if(field.wildCards[conf]?.includes(team))return{tone:"good",points:3};if(Object.entries(field.divisionWinners).some(([division,winner])=>division.startsWith(conf)&&winner===team))return{tone:"warning",points:1};return{tone:"bad",points:0}}
function postseasonPoints(type,team,post){if(!team)return 0;if(type==="conference")return post.conferenceFinalTeams.has(team)?3:0;if(type==="superbowl")return post.superBowl?.teams?.includes(team)?5:0;if(type==="champion")return post.superBowl?.winner===team?5:0;return 0}
function pointCell(points,tone="neutral"){const pointTone=points>0?tone==="warning"?"warning":"good":"neutral";return`<strong class="pick-points ${pointTone}">+${points}</strong>`}
function pickRecordRow(label,team,result){const snapshot=teamSnapshot(team);return`<div class="pick-status-row"><span class="pick-label">${esc(label)}</span><strong class="pick-team">${teamLabel(team)}</strong><span class="team-record ${result.tone}">${recordText(snapshot)}</span>${pointCell(result.points,result.tone)}</div>`}
function aliveState(team,playoffTeams){return team?playoffTeams.has(team):null}
function aliveSummary(teams,playoffTeams){const states=teams.map(team=>aliveState(team,playoffTeams));if(states.some(value=>value===null))return`<span class="alive-summary neutral">Awaiting picks</span>`;const alive=states.filter(Boolean).length;if(alive===2)return`<span class="alive-summary good">Both alive</span>`;if(alive===0)return`<span class="alive-summary bad">Both out</span>`;return`<span class="alive-summary mixed"><b>1 in</b><i>·</i><em>1 out</em></span>`}
function playoffStatusRow(label,team,playoffTeams,points){const alive=aliveState(team,playoffTeams),tone=alive===null?"neutral":alive?"good":"bad",status=alive===null?"—":alive?"IN":"OUT";return`<div class="pick-status-row playoff-row"><span class="pick-label">${esc(label)}</span><strong class="pick-team ${tone}">${teamLabel(team)}</strong><span class="playoff-state ${tone}">${status}</span>${pointCell(points)}</div>`}
function pickGroup(title,rows,summary=""){return`<section class="pick-group"><div class="pick-group-head"><h4>${esc(title)}</h4>${summary}</div>${rows.join("")}</section>`}
function renderPickBreakdowns(){const target=document.querySelector("#pick-breakdowns");if(!target)return;const field=projectedField(),playoffTeams=playoffTeamSet(field),post=postseasonResults(state.snapshot?.games||[]);target.innerHTML=state.participants.slice().sort((a,b)=>a.slot-b.slot).map(participant=>{const pick=pickFor(participant.id),score=scorePick(pick);const divisionRows=Object.keys(DIVISIONS).map(division=>{const team=pick.division_winners?.[division];return pickRecordRow(division,team,divisionResult(team,division,field))});const wildCardRows=["AFC","NFC"].flatMap(conf=>(pick[`${conf.toLowerCase()}_wild_cards`]||[]).concat(Array(3).fill(null)).slice(0,3).map((team,index)=>pickRecordRow(`${conf} WC ${index+1}`,team,wildCardResult(team,conf,field))));const afcTeams=(pick.afc_championship||[]).concat(Array(2).fill(null)).slice(0,2),nfcTeams=(pick.nfc_championship||[]).concat(Array(2).fill(null)).slice(0,2),superBowlTeams=(pick.super_bowl||[]).concat(Array(2).fill(null)).slice(0,2);const afcRows=afcTeams.map((team,index)=>playoffStatusRow(`Finalist ${index+1}`,team,playoffTeams,postseasonPoints("conference",team,post))),nfcRows=nfcTeams.map((team,index)=>playoffStatusRow(`Finalist ${index+1}`,team,playoffTeams,postseasonPoints("conference",team,post))),superBowlRows=superBowlTeams.map((team,index)=>playoffStatusRow(`Team ${index+1}`,team,playoffTeams,postseasonPoints("superbowl",team,post)));superBowlRows.push(playoffStatusRow("Champion",pick.champion,playoffTeams,postseasonPoints("champion",pick.champion,post)));return`<article class="pick-board"><header><div><p class="eyebrow">PLAYER ${participant.slot}</p><h3>${esc(participant.display_name)}</h3></div><div class="pick-board-score"><strong>${score.projected}</strong><span>projected pts</span></div></header><div class="pick-column-head"><span>Pick</span><span>Team</span><span>Status</span><span>Pot. pts</span></div>${pickGroup("Division winners",divisionRows)}${pickGroup("Wild cards",wildCardRows)}${pickGroup("AFC Championship",afcRows,aliveSummary(afcTeams,playoffTeams))}${pickGroup("NFC Championship",nfcRows,aliveSummary(nfcTeams,playoffTeams))}${pickGroup("Super Bowl LXI",superBowlRows,aliveSummary(superBowlTeams,playoffTeams))}</article>`}).join("")}

function pickedTeamCounts(){const counts=new Map();for(const participant of state.participants){const pick=pickFor(participant.id),teams=new Set([...Object.values(pick.division_winners||{}),...(pick.afc_wild_cards||[]),...(pick.nfc_wild_cards||[]),...(pick.afc_championship||[]),...(pick.nfc_championship||[]),...(pick.super_bowl||[]),pick.champion].filter(Boolean));for(const team of teams)counts.set(team,(counts.get(team)||0)+1)}return counts}
function gamesBetween(leader,trailer){return Math.max(0,(((leader?.wins||0)-(trailer?.wins||0))+((trailer?.losses||0)-(leader?.losses||0)))/2)}
function gapText(gap,inside){if(gap===0)return"At cut line";const amount=Number.isInteger(gap)?String(gap):gap.toFixed(1);return`${amount} game${gap===1?"":"s"} ${inside?"ahead":"back"}`}
function nextGameFor(code){const now=Date.now()-12*60*60*1000;return(state.snapshot?.games||[]).filter(game=>!game.completed&&Number(game.seasonType)>=2&&(game.teams||[]).includes(code)&&new Date(game.date).getTime()>=now).sort((a,b)=>new Date(a.date)-new Date(b.date))[0]||null}
function renderBubbleWatch(){const target=document.querySelector("#bubble-watch");if(!target)return;const standings=state.snapshot?.standings?.teams||[],field=projectedField(),inField=playoffTeamSet(field),counts=pickedTeamCounts(),candidates=[];for(const conf of ["AFC","NFC"]){const ranked=standings.filter(team=>team.conference===conf).sort(sortTeams),insideTeams=ranked.filter(team=>inField.has(team.abbr)),outsideTeams=ranked.filter(team=>!inField.has(team.abbr)),lastIn=insideTeams[insideTeams.length-1],firstOut=outsideTeams[0];for(const team of ranked){if(!counts.has(team.abbr)||!lastIn||!firstOut)continue;const inside=inField.has(team.abbr),gap=inside?gamesBetween(team,firstOut):gamesBetween(lastIn,team);if(gap<=2)candidates.push({team,inside,gap,pickedBy:counts.get(team.abbr),rank:ranked.indexOf(team)+1})}}candidates.sort((a,b)=>a.gap-b.gap||Number(a.inside)-Number(b.inside)||b.pickedBy-a.pickedBy||a.rank-b.rank);if(!candidates.length){target.innerHTML='<p class="bubble-empty">No picked teams are within two games of the playoff cut line right now.</p>';return}target.innerHTML=candidates.map(({team,inside,gap,pickedBy,rank})=>{const game=nextGameFor(team.abbr),opponent=game?(game.teams||[]).find(code=>code!==team.abbr):null,next=game?`${opponent?`${esc(opponent)} · ${esc(TEAM_NAMES[opponent]||opponent)} · `:""}${fmtTime(game.date)}`:"Schedule not available";return`<article class="bubble-card"><div class="bubble-card-top"><div><span class="bubble-conf">${team.conference} #${rank}</span><h3>${esc(team.abbr)} · ${esc(TEAM_NAMES[team.abbr]||team.name||"")}</h3></div><strong class="bubble-record">${recordText(team)}</strong></div><div class="bubble-meta"><span class="bubble-gap ${inside?"in":"out"}">${inside?"IN":"OUT"} · ${gapText(gap,inside)}</span><span>Picked by ${pickedBy} player${pickedBy===1?"":"s"}</span></div><div class="bubble-next"><small>NEXT MATCHUP</small><strong>${next}</strong></div></article>`}).join("")}
function renderMeta(){document.querySelector("#last-update").textContent=fmtTime(state.snapshot?.updated_at);document.querySelector("#season-status").textContent=(state.snapshot?.phase||"preseason").toUpperCase();document.querySelector("#standings-note").textContent=`Week ${state.snapshot?.week||"—"} · Updated ${fmtTime(state.snapshot?.updated_at)}`}
function renderLeaderboard(){const rows=state.participants.map(p=>({p,s:scorePick(pickFor(p.id))})).sort((a,b)=>b.s.projected-a.s.projected||a.p.slot-b.p.slot);document.querySelector("#leaderboard").classList.remove("loading-card");document.querySelector("#leaderboard").innerHTML=rows.map((r,i)=>`<article class="leader-card ${i===0?'first':''}" data-rank="${i+1}"><div class="leader-top"><span class="rank">#${i+1} PROJECTED</span><i class="status-dot"></i></div><h3>${esc(r.p.display_name)}</h3><div class="score-row"><strong class="big-score">${r.s.projected}</strong><span>POINTS</span></div><div class="mini-stats"><span>REGULAR <b>${r.s.regular}</b></span><span>POSTSEASON <b>${r.s.postseason}</b></span><span>MAX <b>${r.s.max}</b></span></div></article>`).join("")}
function renderPlayoff(){const field=projectedField(),teams=state.snapshot?.standings?.teams||[];const html=["AFC","NFC"].map(conf=>{const entries=[...Object.entries(field.divisionWinners).filter(([d])=>d.startsWith(conf)).map(([,t])=>t),...field.wildCards[conf]].map(code=>teams.find(t=>t.abbr===code)||{abbr:code,wins:0,losses:0}).sort(sortTeams);return`<div><div class="conf-label">${conf}</div>${entries.length?entries.map((t,i)=>`<div class="seed-row"><span class="seed">${i+1}</span><span class="team-code">${esc(t.abbr)} · ${esc(TEAM_NAMES[t.abbr]||t.name||"")}</span><span class="record">${t.wins||0}–${t.losses||0}${t.ties?`–${t.ties}`:""}</span></div>`).join(""):'<p class="empty">Standings will appear after the first sync.</p>'}</div>`}).join("");document.querySelector("#playoff-picture").innerHTML=html}
function renderPlayers(){document.querySelector("#player-cards").innerHTML=state.participants.map(p=>{const pick=pickFor(p.id),count=pickCount(p),s=scorePick(pick);return`<article class="player-card"><div class="player-avatar">${esc(p.display_name[0]||p.slot)}</div><h3>${esc(p.display_name)}</h3><p class="pick-status">${p.locked?"Picks locked":count===21?"All picks entered":`${count} of 21 selections`}</p><div class="progress"><i style="width:${Math.min(100,count/21*100)}%"></i></div><div class="mini-stats"><span>PROJECTED <b>${s.projected}</b></span><span>MAX <b>69</b></span></div><button class="edit-btn" data-edit="${p.id}">${p.locked?"Review picks":"Enter picks"}</button></article>`}).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEditor(b.dataset.edit))}
function divisionCards(conf){const teams=(state.snapshot?.standings?.teams||[]).filter(t=>t.conference===conf);return Object.keys(DIVISIONS).filter(d=>d.startsWith(conf)).map(div=>{const rows=teams.filter(t=>t.division===div).sort(sortTeams);return`<article class="division-card"><h3>${div}</h3><div class="table-row header"><span>#</span><span>TEAM</span><span>W–L</span><span>PCT</span></div>${rows.length?rows.map((t,i)=>`<div class="table-row ${i===0?'playoff':''}"><span>${i+1}</span><strong>${esc(t.abbr)} · ${esc(TEAM_NAMES[t.abbr]||t.name||"")}</strong><span>${t.wins||0}–${t.losses||0}${t.ties?`–${t.ties}`:""}</span><span>${Number(t.pct||0).toFixed(3).replace(/^0/,"")}</span></div>`).join(""):'<p class="empty" style="padding-left:18px">No standings data yet.</p>'}</article>`}).join("")}
function renderStandings(){document.querySelector("#standings-grid").innerHTML=divisionCards(state.conference)}
function renderDashboardStandings(){const target=document.querySelector("#dashboard-standings");if(!target)return;const all=state.snapshot?.standings?.teams||[];target.innerHTML=["AFC","NFC"].map(conf=>{const count=all.filter(team=>team.conference===conf).length;return`<section class="conference-board"><div class="conference-board-head"><strong>${conf}</strong><span>${count} of 16 teams</span></div><div class="dashboard-division-list">${divisionCards(conf)}</div></section>`}).join("")}

function options(list,current,blank="Select team"){return`<option value="">${blank}</option>`+list.map(t=>`<option value="${t}" ${current===t?'selected':''}>${t} · ${TEAM_NAMES[t]}</option>`).join("")}
function field(label,name,list,current){return`<div class="field"><label>${label}</label><select name="${name}">${options(list,current)}</select></div>`}
function openEditor(id){const p=state.participants.find(x=>x.id===id),pick=pickFor(id);const divisionFields=Object.entries(DIVISIONS).map(([d,teams])=>field(d,`div:${d}`,teams,pick.division_winners?.[d])).join("");const repeat=(label,prefix,list,values,n)=>Array.from({length:n},(_,i)=>field(`${label} ${i+1}`,`${prefix}:${i}`,list,values?.[i])).join("");document.querySelector("#editor-content").innerHTML=`<form id="pick-form"><div class="editor-header"><p class="eyebrow">PLAYER ${p.slot}</p><h2 id="editor-title">${esc(p.display_name)}'s picks</h2><p>Use your private PIN to save changes. Everyone can review the final board.</p></div><div class="field-group"><h3>Profile</h3><div class="form-grid">${fieldInput("Display name","display_name",p.display_name)}</div></div><div class="field-group"><h3>Division winners</h3><p class="field-help">3 points each · 1 point if the team makes it as a wild card</p><div class="form-grid">${divisionFields}</div></div><div class="field-group"><h3>Wild cards</h3><p class="field-help">Three per conference · 3 points exact, 1 point if they win the division</p><div class="form-grid">${repeat("AFC wild card","afcwc",CONF.AFC,pick.afc_wild_cards,3)}${repeat("NFC wild card","nfcwc",CONF.NFC,pick.nfc_wild_cards,3)}</div></div><div class="field-group"><h3>Conference championships</h3><p class="field-help">3 points for each team that reaches the game</p><div class="form-grid">${repeat("AFC finalist","afcc",CONF.AFC,pick.afc_championship,2)}${repeat("NFC finalist","nfcc",CONF.NFC,pick.nfc_championship,2)}</div></div><div class="field-group"><h3>Super Bowl LXI</h3><p class="field-help">5 points per team · plus 5 for the champion</p><div class="form-grid">${repeat("Super Bowl team","sb",[...CONF.AFC,...CONF.NFC],pick.super_bowl,2)}${field("Champion","champ",[...CONF.AFC,...CONF.NFC],pick.champion)}</div></div><div class="pin-row"><div class="field"><label>PRIVATE PIN</label><input required name="pin" inputmode="numeric" autocomplete="current-password" placeholder="Enter your PIN"></div></div><button class="save-btn" type="submit">Save all picks</button></form>`;const modal=document.querySelector("#editor");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";document.querySelector("#pick-form").onsubmit=e=>savePicks(e,p)}
function fieldInput(label,name,value){return`<div class="field"><label>${label}</label><input name="${name}" maxlength="40" value="${esc(value)}"></div>`}
function formArray(fd,prefix,n){return Array.from({length:n},(_,i)=>fd.get(`${prefix}:${i}`)).filter(Boolean)}
async function savePicks(e,participant){e.preventDefault();const btn=e.submitter,fd=new FormData(e.currentTarget),pin=fd.get("pin"),division_winners={};for(const d of Object.keys(DIVISIONS)){const v=fd.get(`div:${d}`);if(v)division_winners[d]=v}const payload={division_winners,afc_wild_cards:formArray(fd,"afcwc",3),nfc_wild_cards:formArray(fd,"nfcwc",3),afc_championship:formArray(fd,"afcc",2),nfc_championship:formArray(fd,"nfcc",2),super_bowl:formArray(fd,"sb",2),champion:fd.get("champ")||null,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()};const error=validate(payload);if(error)return toast(error);btn.disabled=true;btn.textContent="Saving…";try{await Promise.all([api(`participants?id=eq.${participant.id}`,{method:"PATCH",headers:{"x-player-pin":pin},body:JSON.stringify({display_name:fd.get("display_name").trim(),updated_at:new Date().toISOString()})}),api(`picks?participant_id=eq.${participant.id}`,{method:"PATCH",headers:{"x-player-pin":pin},body:JSON.stringify(payload)})]);closeEditor();await load();toast("Picks saved") }catch(err){console.error(err);toast("PIN was incorrect or the save failed");btn.disabled=false;btn.textContent="Save all picks"}}
function validate(p){for(const conf of ["afc","nfc"]){const wc=p[`${conf}_wild_cards`];if(new Set(wc).size!==wc.length)return`${conf.toUpperCase()} wild cards cannot repeat`;const cc=p[`${conf}_championship`];if(new Set(cc).size!==cc.length)return`${conf.toUpperCase()} finalists cannot repeat`}if(new Set(p.super_bowl).size!==p.super_bowl.length)return"Super Bowl teams cannot repeat";if(p.super_bowl.length===2&&!(CONF.AFC.includes(p.super_bowl[0])!==CONF.AFC.includes(p.super_bowl[1])))return"Choose one AFC and one NFC Super Bowl team";if(p.champion&&p.super_bowl.length===2&&!p.super_bowl.includes(p.champion))return"Champion must be one of your Super Bowl teams";return null}
function closeEditor(){document.querySelector("#editor").classList.remove("open");document.querySelector("#editor").setAttribute("aria-hidden","true");document.body.style.overflow=""}
function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2800)}
async function sync(){const buttons=[document.querySelector("#refresh-btn"),document.querySelector("#refresh-btn-2")];buttons.forEach(b=>{b.disabled=true;b.textContent="Refreshing…"});try{const r=await fetch("/api/sync",{method:"POST"});if(!r.ok)throw new Error(await r.text());await load();toast("Standings updated")}catch(e){console.error(e);toast("Live update unavailable. Try again shortly.")}finally{buttons.forEach(b=>{b.disabled=false;b.textContent="Refresh standings"})}}
function route(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===name));document.querySelectorAll(".topbar [data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===name));history.replaceState(null,"",`#${name}`);scrollTo(0,0)}
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>route(b.dataset.route));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeEditor);document.querySelectorAll("[data-conf]").forEach(b=>b.onclick=()=>{state.conference=b.dataset.conf;document.querySelectorAll("[data-conf]").forEach(x=>x.classList.toggle("active",x===b));renderStandings()});document.querySelector("#refresh-btn").onclick=sync;document.querySelector("#refresh-btn-2").onclick=sync;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeEditor()});route(location.hash.slice(1)||"dashboard");load();
