type Team = {abbr:string;name:string;conference:string;division:string;wins:number;losses:number;ties:number;pct:number;playoffSeed:number|null;divisionRank:number|null};
declare const Netlify:{env:{get:(key:string)=>string|undefined}};
const STANDINGS="https://site.api.espn.com/apis/v2/sports/football/nfl/standings?region=us&lang=en&contentorigin=espn&type=0&level=3&sort=playoffseed%3Aasc&season=2026";
const SCOREBOARD="https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=2026&limit=1000";

function stat(entry:any,name:string){const s=(entry.stats||[]).find((x:any)=>x.name===name||x.abbreviation===name);return Number(s?.value ?? s?.displayValue ?? 0)}
function normalizeStandings(data:any):Team[]{const out:Team[]=[];for(const conf of data.children||[]){const conference=String(conf.name||conf.abbreviation||"").includes("AFC")?"AFC":"NFC";for(const div of conf.children||[]){const raw=String(div.name||div.abbreviation||"");const division=raw.replace("American Football Conference","AFC").replace("National Football Conference","NFC").replace(" - "," ");for(const entry of div.standings?.entries||[]){const team=entry.team||{};out.push({abbr:team.abbreviation,name:team.displayName||team.name,conference,division,wins:stat(entry,"wins"),losses:stat(entry,"losses"),ties:stat(entry,"ties"),pct:stat(entry,"winPercent"),playoffSeed:stat(entry,"playoffSeed")||null,divisionRank:stat(entry,"divisionRank")||null})}}}return out}
function normalizeGames(data:any){return(data.events||[]).map((e:any)=>{const c=e.competitions?.[0]||{},teams=(c.competitors||[]).map((x:any)=>x.team?.abbreviation).filter(Boolean),winner=(c.competitors||[]).find((x:any)=>x.winner)?.team?.abbreviation;return{id:e.id,date:e.date,name:e.shortName||e.name,completed:!!e.status?.type?.completed,seasonType:Number(e.season?.type||e.seasonType?.type||0),week:Number(e.week?.number||0),teams,winner:winner||null}})}

export default async (_req:Request)=>{try{const supabaseUrl=Netlify.env.get("SUPABASE_URL"),key=Netlify.env.get("SUPABASE_KEY"),secret=Netlify.env.get("NFL_SYNC_SECRET");if(!supabaseUrl||!key||!secret)throw new Error("Missing server configuration");const [standingsRes,gamesRes]=await Promise.all([fetch(STANDINGS),fetch(SCOREBOARD)]);if(!standingsRes.ok||!gamesRes.ok)throw new Error(`NFL feed unavailable: ${standingsRes.status}/${gamesRes.status}`);const [standingsData,gamesData]=await Promise.all([standingsRes.json(),gamesRes.json()]);const teams=normalizeStandings(standingsData),games=normalizeGames(gamesData);if(teams.length!==32)throw new Error(`Expected 32 NFL teams, received ${teams.length}`);const week=Number(gamesData.week?.number||gamesData.leagues?.[0]?.calendar?.find((x:any)=>x.value===gamesData.season?.type)?.entries?.find((x:any)=>new Date(x.startDate)<=new Date()&&new Date(x.endDate)>=new Date())?.value||0)||null;const phase=gamesData.season?.type===3?"postseason":gamesData.season?.type===1?"preseason":"regular";const res=await fetch(`${supabaseUrl}/rest/v1/nfl_snapshot?id=eq.1`,{method:"PATCH",headers:{apikey:key,"Content-Type":"application/json",Prefer:"return=representation","x-sync-secret":secret},body:JSON.stringify({season:2026,week,phase,standings:{teams},games,updated_at:new Date().toISOString()})});if(!res.ok)throw new Error(`Database update failed: ${await res.text()}`);return Response.json({ok:true,teams:teams.length,week,updatedAt:new Date().toISOString()})}catch(error){console.error(error);return Response.json({ok:false,error:error instanceof Error?error.message:"Unknown error"},{status:500})}};

export const config={path:"/api/sync"};
